config/routes.rb
EndSchoolViolence::Application.routes.draw do
  devise_for :users
  get "static_pages/about"
  get "static_pages/contact"
  resources :pledges
  resources :forums

  root 'welcome#index'

end

app/models/forum.rb
class Forum < ActiveRecord::Base
end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
	validates_presence_of :first_name, :last_name, :zip
	validates_uniqueness_of :email
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_action :set_forum, only: [:show, :edit, :update, :destroy]

  # GET /forums
  # GET /forums.json
  def index
    @forums = Forum.all
  end

  # GET /forums/1
  # GET /forums/1.json
  def show
  end

  # GET /forums/new
  def new
    @forum = Forum.new
  end

  # GET /forums/1/edit
  def edit
  end

  # POST /forums
  # POST /forums.json
  def create
    @forum = Forum.new(forum_params)

    respond_to do |format|
      if @forum.save
        format.html { redirect_to @forum, notice: 'Forum was successfully created.' }
        format.json { render action: 'show', status: :created, location: @forum }
      else
        format.html { render action: 'new' }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forums/1
  # PATCH/PUT /forums/1.json
  def update
    respond_to do |format|
      if @forum.update(forum_params)
        format.html { redirect_to @forum, notice: 'Forum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1
  # DELETE /forums/1.json
  def destroy
    @forum.destroy
    respond_to do |format|
      format.html { redirect_to forums_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum
      @forum = Forum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forum_params
      params.require(:forum).permit(:title, :body, :author)
    end
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
  before_action :set_pledge, only: [:show, :edit, :update, :destroy]

  # GET /pledges
  # GET /pledges.json
  def index
    @pledges = Pledge.all
  end

  # GET /pledges/1
  # GET /pledges/1.json
  def show
  end

  # GET /pledges/new
  def new
    @pledge = Pledge.new
  end

  # GET /pledges/1/edit
  def edit
  end

  # POST /pledges
  # POST /pledges.json
  def create
    @pledge = Pledge.new(pledge_params)

    respond_to do |format|
      if @pledge.save
        format.html { redirect_to @pledge, notice: 'Pledge was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pledge }
      else
        format.html { render action: 'new' }
        format.json { render json: @pledge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pledges/1
  # PATCH/PUT /pledges/1.json
  def update
    respond_to do |format|
      if @pledge.update(pledge_params)
        format.html { redirect_to @pledge, notice: 'Pledge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pledge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pledges/1
  # DELETE /pledges/1.json
  def destroy
    @pledge.destroy
    respond_to do |format|
      format.html { redirect_to pledges_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pledge
      @pledge = Pledge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pledge_params
      params.require(:pledge).permit(:first_name, :last_name, :email, :city, :state, :zip)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/forums/_form.html.haml
= form_for @forum do |f|
  - if @forum.errors.any?
    #error_explanation
      %h2= "#{pluralize(@forum.errors.count, "error")} prohibited this forum from being saved:"
      %ul
        - @forum.errors.full_messages.each do |msg|
          %li= msg
  
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :author
    = f.text_field :author
  .actions
    = f.submit 'Submit'

app/views/forums/edit.html.haml
%h1 Editing forum

= render 'form'

= link_to 'Show', @forum
\|
= link_to 'Back', forums_path

app/views/forums/index.html.haml
%h1 Listing forums

%table
  %tr
    %th Title
    %th 
    %th Author
    %th
    %th
    %th

  - @forums.each do |forum|
    %tr
      %td= forum.title
      / %td= truncate forum.body, length: 100
      %td= forum.author
      %td= link_to 'Show', forum
      / %td= link_to 'Edit', edit_forum_path(forum)
      / %td= link_to 'Destroy', forum, :method => :delete, :data => { :confirm => 'Are you sure?' }

/ %br

/ = link_to 'New Forum', new_forum_path

app/views/forums/new.html.haml
%h1 New forum

= render 'form'

= link_to 'Back', forums_path

app/views/forums/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @forum.title
%p
  %b Body:
  = @forum.body
%p
  %b Author:
  = @forum.author

= link_to 'Edit', edit_forum_path(@forum)
\|
= link_to 'Back', forums_path

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><a href="/pledges/new.html">Sign the Pledge</a></li>
<li><a href="/static_pages/about.html">About</a></li>
<!-- <li><a href="/forums.html">Forum</a></li> -->

<% if user_signed_in? %>
  <!-- <li><%= link_to 'Create Topic', new_forum_path %></li> -->
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Honor with Action" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Honor with Action Claire Davis" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <link type="text/css" rel="stylesheet" href="honorwithaction.css"/>
    <link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Cabin" rel="stylesheet" type="text/css">
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <% if notice %>
         <p class="alert alert-notice"><%= notice %></p>
       <% end %>
       <% if alert %>
         <p class="alert alert-error"><%= alert %></p>
       <% end %>
       <p class="navbar-text pull-right">
       <% if user_signed_in? %>
         Logged in as <strong><%= current_user.email %></strong>.
         <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
         <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
       <% end %>
       <%= yield %>
    </main>
    <footer>
        <div class="row">
          <div class="col-lg-4">

            <p>Copyright &copy; Honor with Action 2014</p>
            <p>Connect on Twitter </p> 
            <div class="site-footer">
                  <div class="row">
                    <div class="column"> 
                      <a href="https://twitter.com/honorwithaction"><img src="/assets/twitter.png" alt="Follow Honor with Action">
                    </div>
                  </div>
          </div>
        </div>
      </footer>
  </body>
</html>

app/views/pledges/_form.html.haml
= form_for @pledge do |f|
  - if @pledge.errors.any?
    #error_explanation
      %h2= "#{pluralize(@pledge.errors.count, "error")} prohibited this pledge from being saved:"
      %ul
        - @pledge.errors.full_messages.each do |msg|
          %li= msg

  .field 
    = f.label :first_name
    =f.text_field :first_name, class: 'form-control', autofocus: true, placeholder: 'First Name'
  .field
    = f.label :last_name
    = f.text_field :last_name, class: 'form-control', autofocus: true, placeholder: 'Last Name'
  .field 
    = f.label :email
    = f.text_field :email, class: 'form-control', autofocus: true, placeholder: 'Email'
  .field
    = f.label :city
    = f.text_field :city, class: 'form-control', autofocus: true, placeholder: 'City'
  .field
    = f.label :state
    = f.text_field :state, class: 'form-control', autofocus: true, placeholder: 'State'
  .field
    = f.label :zip
    = f.text_field :zip, class: 'form-control', autofocus: true, placeholder: 'Zip Code'
  .actions
    = f.submit 'Save'

app/views/pledges/edit.html.haml
%h1 Editing pledge

= render 'form'

= link_to 'Show', @pledge
\|
= link_to 'Back', pledges_path

app/views/pledges/index.html.haml
%h1 Listing pledges

%table
  %tr
    %th First name
    %th Last name
    %th Email
    %th City
    %th State
    %th Zip
    %th
    %th
    %th

  - @pledges.each do |pledge|
    %tr
      %td= pledge.first_name
      %td= pledge.last_name
      %td= pledge.email
      %td= pledge.city
      %td= pledge.state
      %td= pledge.zip
      %td= link_to 'Show', pledge
      %td= link_to 'Edit', edit_pledge_path(pledge)
      %td= link_to 'Destroy', pledge, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Pledge', new_pledge_path

app/views/pledges/new.html.haml
%h2 
  %em I pledge to make my actions echo so loudly in honor of Claire that you will not be able to hear my words!!!

= render 'form'

= link_to 'Back', pledges_path

app/views/pledges/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @pledge.first_name
%p
  %b Last name:
  = @pledge.last_name
%p
  %b Email:
  = @pledge.email
%p
  %b City:
  = @pledge.city
%p
  %b State:
  = @pledge.state
%p
  %b Zip:
  = @pledge.zip

= link_to 'Edit', edit_pledge_path(@pledge)
\|
= link_to 'Back', pledges_path

app/views/static_pages/about.html.haml
%h1 Honor with Action
.row
  .col-md-2.blog-main
  .col-md-8.blog-main
      
    %h3 Honor with Action is a grassroots, community based organization whose mission is to honor through action all victims of gun violence and transform our communities. 
	 
 



.widewrapper.main
  .container
    .row
      .col-md-2.blog-main
      .col-md-8.blog-main
  
        %p Honor with action began one day shortly after the shooting at Arapahoe High school when someone asked me "what are you tolerating?" Much to my shock and shame, the answer that leapt forth to mind was, I am tolerating school shootings.

        %p There it was, the elephant was out in the room. I had become by my lack of action a co-conspirator to the endless stream of school shootings. I complained about the lack of action from my elected officials. I wanted them to solve the problem so I wouldn't have to get my hands dirty.
        
        %p I lived through the horror of Columbine, Platte Canyon High School, a shooting at a theatre less than a mile from my house where 12 people were gunned down. Five months later I watched in horror as 20 children and six teachers were murdered. I wondered how high would the body count have to become before Washington would be compelled to act.

        %p For me the tipping point was another shooting in my community. Claire Davis, a young vibrant girl in her senior year of high school was gunned down because she was in the wrong place at the wrong time. The only thing Claire did wrong that day was to go to school. I had done nothing and now another person in my community was fighting for her life.

        %p That was it for me. I couldn't wait for the next school shooting and there will be another one and we will weep again and wonder what will it take for someone else to solve this problem. I don't pretend to have an answer to this and I can't wait any more. I choose to honor Claire with action.

        %p I picked up the phone and called my state congresswoman, my Colorado state senator. I called my congressman and senators in Washington. I left a message with the Governor of Colorado. I have received no response from any of them yet.

        %p Tomorrow I will join thousands of Coloradans at Claire's memorial and we will celebrate and honor her life. 

        %p Tomorrow this website will launch for Claire and I invite you to pledge to take action to honor Claire. I don't know what that will look like for each of you.

        %p Maybe taking action will be as simple as smiling at a stranger that you pass during the day. Maybe you be inspired to perform a random act of kindness. Maybe you will be inspired to a life of service. I hope you will join with me and take action with honor for Claire.

        %p
          Follow Honor with Action on
          %a#active{:href => "https://twitter.com/honorwithaction"} Twitter
          and tweet your intentions to honor Claire using the hashtags #honorwithaction, #ClaireDavis, #FLRC
  

  		
  

app/views/static_pages/contact.html.haml
%h1 StaticPages#contact
%p Find me in app/views/static_pages/contact.html.haml

app/views/welcome/index.html.haml
%h1 Honor with Action

%h3
  %em On December 13, 2013 another school shooting occurred at a high school in Colorado. A young girl, armed only with kindness, who loved horses was shot at point blank range and passed away eight days later. 

%h4
  %em This website is dedicated to
  %a#active{:href => "http://thecoloradoobserver.com/2013/12/colorados-focus-on-claire-davis-writes-new-ending-to-familiar-mass-shooting-tale/"} the life of Claire Davis
  who touched the lives of many Coloradan's after she was shot by a classmate at Araphoe High School.
  %h4 Please take a minute and sign the pledge to honor Claire with action, whatever that looks like for you.

  %h5
  = link_to 'Sign the pledge', new_pledge_path, class: "btn btn-primary"